[package]
name = "dtemu"
version = "0.1.0"
edition = "2021"
description = "Digitakt mk1 (OS 1.53) emulator: ColdFire MCF5441x in Rust"
license = "MIT"

[dependencies]
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
lz4_flex = "0.11"
serde-big-array = "0.5"
minifb = { version = "0.27", default-features = false, features = ["x11"] }
cpal = "0.15"
png = "0.17"
cranelift-codegen = "0.134"
cranelift-frontend = "0.134"
cranelift-jit = "0.134"
cranelift-module = "0.134"
cranelift-native = "0.134"

[profile.release]
debug = 1
lto = "thin"
codegen-units = 1

[profile.dev]
opt-level = 2
